name: Docker Image CI

on: push

jobs:

  build-image:
    name: Build docker images
    if: startsWith(github.event.ref, 'refs/tags/v')

    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
      id-token: write

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
  
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to ghcr.io
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - id: auth
        name: Authenticate with Google Cloud
        uses: google-github-actions/auth@v2
        with:
          token_format: access_token
          workload_identity_provider: projects/664567181123/locations/global/workloadIdentityPools/camels-de-github/providers/github
          service_account: camels-image-uploader@camels-de.iam.gserviceaccount.com
          access_token_lifetime: 300s
        
      - name: Login to Artifact Registry
        uses: docker/login-action@v1
        with:
          registry: europe-west3-docker.pkg.dev
          username: oauth2accesstoken
          password: ${{ steps.auth.outputs.access_token }}
      
      - name: Get tag
        id: get-tag
        run: echo ::set-output name=short_ref::${GITHUB_REF#refs/*/}
    
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ghcr.io/camels-de/clipper

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: | 
            ${{ steps.meta.outputs.tags }}
            europe-west3-docker.pkg.dev/camels-de/camels-de-clipper/clipper:${{ steps.get-tag.outputs.short_ref }}
            europe-west3-docker.pkg.dev/camels-de/camels-de-clipper/clipper:latest
          labels: ${{ steps.meta.outputs.labels }}
